#if !canImport(ObjectiveC)
import XCTest

extension ParserDescriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserDescriptionTests = [
        ("testCoding", testCoding),
        ("testCompilation", testCompilation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParserDescriptionTests.__allTests__ParserDescriptionTests),
    ]
}
#endif
